-- ==============================================================================
-- Gym Track - Supabase Database Schema
-- ==============================================================================
-- Execute este script no SQL Editor do painel do seu Supabase para criar
-- todas as tabelas, índices e funções RPC necessárias para o funcionamento do app.

-- 1. EXTENSÕES
create extension if not exists "uuid-ossp";

-- 2. TABELA: routines (Fichas / Rotinas de Treino)
create table if not exists public.routines (
    id uuid primary key default uuid_generate_v4(),
    user_id uuid references auth.users(id) on delete cascade not null,
    name text not null,
    day_of_week text,
    shared_from uuid,
    creator_name text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. TABELA: exercises (Exercícios vinculados a uma rotina)
create table if not exists public.exercises (
    id bigint generated by default as identity primary key,
    routine_id uuid references public.routines(id) on delete cascade not null,
    name text not null,
    sets integer default 3,
    reps text default '10-12',
    weight numeric default 0,
    rest_seconds integer default 60,
    order_index integer default 0,
    notes text,
    bi_set_group text,
    is_cardio boolean default false,
    target_time integer,
    target_distance numeric,
    progression_type text,
    progression_value numeric,
    reps_min integer,
    reps_max integer,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. TABELA: sessions (Histórico de treinos executados)
create table if not exists public.sessions (
    id uuid primary key default uuid_generate_v4(),
    user_id uuid references auth.users(id) on delete cascade not null,
    routine_id uuid,
    routine_name text,
    date timestamp with time zone default timezone('utc'::text, now()) not null,
    duration integer default 0,
    exercises jsonb default '[]'::jsonb,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. TABELA: weight_logs (Histórico de Peso)
create table if not exists public.weight_logs (
    id uuid primary key default uuid_generate_v4(),
    user_id uuid references auth.users(id) on delete cascade not null,
    value numeric not null,
    date date not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. TABELA: bf_logs (Histórico de Gordura Corporal %)
create table if not exists public.bf_logs (
    id uuid primary key default uuid_generate_v4(),
    user_id uuid references auth.users(id) on delete cascade not null,
    value numeric not null,
    date date not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 7. TABELA: measurements (Medidas Corporais)
create table if not exists public.measurements (
    id uuid primary key default uuid_generate_v4(),
    user_id uuid references auth.users(id) on delete cascade not null,
    date date not null,
    chest numeric,
    arms numeric,
    waist numeric,
    hips numeric,
    thighs numeric,
    calves numeric,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 8. TABELA: user_goals (Metas Gerais, PRs e Desafios)
create table if not exists public.user_goals (
    user_id uuid primary key references auth.users(id) on delete cascade,
    free_goals jsonb default '[]'::jsonb,
    pr_goals jsonb default '[]'::jsonb,
    volume_goal jsonb default '{}'::jsonb,
    monthly_target integer default 16,
    body_goals jsonb default '{}'::jsonb,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 9. TABELA: diet_goals (Metas de Macronutrientes)
create table if not exists public.diet_goals (
    user_id uuid primary key references auth.users(id) on delete cascade,
    calories numeric default 2000,
    protein numeric default 150,
    carbs numeric default 200,
    fat numeric default 67,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 10. TABELA: diet_logs (Diário de Alimentos)
create table if not exists public.diet_logs (
    id uuid primary key default uuid_generate_v4(),
    user_id uuid references auth.users(id) on delete cascade not null,
    date date not null,
    meal_type text not null,
    name text not null,
    calories numeric not null,
    protein numeric not null,
    carbs numeric not null,
    fat numeric not null,
    quantity numeric default 1,
    unit text default 'g',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 11. TABELA: user_gamification (XP, Nível e Conquistas)
create table if not exists public.user_gamification (
    user_id uuid primary key references auth.users(id) on delete cascade,
    xp integer default 0,
    level integer default 1,
    badges jsonb default '[]'::jsonb,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ==============================================================================
-- POLÍTICAS DE SEGURANÇA (Row Level Security - RLS)
-- ==============================================================================

alter table public.routines enable row level security;
alter table public.exercises enable row level security;
alter table public.sessions enable row level security;
alter table public.weight_logs enable row level security;
alter table public.bf_logs enable row level security;
alter table public.measurements enable row level security;
alter table public.user_goals enable row level security;
alter table public.diet_goals enable row level security;
alter table public.diet_logs enable row level security;
alter table public.user_gamification enable row level security;

-- Políticas de acesso para cada usuário manipular apenas seus próprios registros
create policy "Users can manage their routines" on public.routines
    for all using (auth.uid() = user_id or shared_from is not null);

create policy "Users can manage exercises" on public.exercises
    for all using (
        exists (
            select 1 from public.routines
            where routines.id = exercises.routine_id
            and (routines.user_id = auth.uid() or routines.shared_from is not null)
        )
    );

create policy "Users can manage sessions" on public.sessions
    for all using (auth.uid() = user_id);

create policy "Users can manage weight logs" on public.weight_logs
    for all using (auth.uid() = user_id);

create policy "Users can manage bf logs" on public.bf_logs
    for all using (auth.uid() = user_id);

create policy "Users can manage measurements" on public.measurements
    for all using (auth.uid() = user_id);

create policy "Users can manage user goals" on public.user_goals
    for all using (auth.uid() = user_id);

create policy "Users can manage diet goals" on public.diet_goals
    for all using (auth.uid() = user_id);

create policy "Users can manage diet logs" on public.diet_logs
    for all using (auth.uid() = user_id);

create policy "Users can manage gamification" on public.user_gamification
    for all using (auth.uid() = user_id);

-- ==============================================================================
-- FUNÇÕES RPC (Autenticação por Username)
-- ==============================================================================

-- 1. Checa se um username já está em uso
create or replace function public.check_username_exists(p_username text)
returns boolean
language plpgsql
security definer
as $$
begin
  return exists (
    select 1 from auth.users
    where lower(raw_user_meta_data->>'username') = lower(p_username)
  );
end;
$$;

-- 2. Retorna o email do usuário a partir do username (usado no login)
create or replace function public.get_user_email(p_username text)
returns text
language plpgsql
security definer
as $$
declare
  v_email text;
begin
  select email into v_email
  from auth.users
  where lower(raw_user_meta_data->>'username') = lower(p_username)
  limit 1;
  return v_email;
end;
$$;
